export const ERROR_CODES = {
    BAD_REQUEST_CODE: 400,
    UNAUTHORIZED_CODE: 401,
    FORBIDDEN_CODE: 403,
    NOT_FOUND_CODE: 404,
    UNPROCESSABLE_ENTITY_CODE: 422,
    INTERNAL_SERVER_ERROR_CODE: 500,
}